apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: dev-core-landscaperdeployment
spec:
  name: dev-core-landscaperdeployment
  description: Number of LandscapperDeplyoments in the LS-DEV-CORE cluster
  target:
    kind: LandscaperDeployment
    group: landscaper-service.gardener.cloud
    version: v1alpha1
  interval: "1m" # in minutes
  # Uses default DataSink (named "default" in metrics-operator-system namespace)
  # To use a custom DataSink, uncomment and specify:
  # dataSinkRef:
  #   name: custom-sink
---
