# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: co-monitor-co-metrics-operator
rules:
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts/token" ]
    verbs: [ "create" ]
  - apiGroups: [""]
    resources: ["events"]
    verbs:
      - '*'
  - apiGroups:
      - landscaper-service.gardener.cloud
    resources:
      - landscaperdeployments
    verbs:
      - '*'
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - insight.orchestrate.cloud.sap
    resources:
      - managedmetrics
      - metrics
      - metrics/status
      - managedmetrics/status
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
