apiVersion: metrics.cloud.sap/v1beta1
kind: FederatedMetric
metadata:
  name: xfed-crds-del
spec:
  name: xfed-crds-del
  description: subaccounts
  target:
    group:  apiextensions.k8s.io
    resource: customresourcedefinitions
    version: v1
  fieldSelector: "metadata.deletionTimestamp"
  checkInterval: "1m" # in minutes
  projections:
    - name: deletion
      fieldPath: "metadata.deletionTimestamp"
    - name: crd.name
      fieldPath: "metadata.name"
  federateCaRef:
    name: federate-ca-sample
    namespace: default
---
