apiVersion: metrics.cloud.sap/v1alpha1
kind: FederatedMetric
metadata:
  name: xfed-entitlements
spec:
  name: xfed-entitlements
  description: entitlements
  target:
    group:  account.btp.orchestrate.cloud.sap
    kind: Entitlement
    version: v1alpha1
  interval: "1m" # in minutes
  projections:
    - name: servicename
      fieldPath: "spec.forProvider.serviceName"
  federateClusterAccessRef:
    name: federate-ca-sample
    namespace: default
---
