apiVersion: metrics.openmcp.cloud/v1alpha1
kind: FederatedMetric
metadata:
  name: xfed-instances
spec:
  name: xfed-instances
  description: service instances
  target:
    group:  services.cloud.sap.com
    kind: ServiceInstance
    version: v1
  interval: "1m" # in minutes
  federateClusterAccessRef:
    name: federate-ca-sample
    namespace: default
---
