apiVersion: metrics.openmcp.cloud/v1alpha1
kind: FederatedMetric
metadata:
  name: xfed-subaccounts
spec:
  name: xfed-subaccounts
  description: subaccounts
  target:
    group:  account.btp.sap.crossplane.io
    kind: Subaccount
    version: v1alpha1
  interval: "1m" # in minutes
  projections:
    - name: region
      fieldPath: "spec.forProvider.region"
  federateClusterAccessRef:
    name: federate-ca-sample
    namespace: default
---
