# permissions for end users to view clientconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clientconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: co-metrics-operator
    app.kubernetes.io/part-of: co-metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: clientconfig-viewer-role
rules:
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - clientconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - clientconfigs/status
  verbs:
  - get
