# permissions for end users to view clusteraccesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusteraccess-viewer-role
rules:
- apiGroups:
  - metrics.openmcp.cloud
  resources:
  - clusteraccesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.openmcp.cloud
  resources:
  - clusteraccesses/status
  verbs:
  - get
