# permissions for end users to view datasinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: datasink-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: metrics-operator
    app.kubernetes.io/part-of: metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: datasink-viewer-role
rules:
- apiGroups:
  - metrics.openmcp.cloud
  resources:
  - datasinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.openmcp.cloud
  resources:
  - datasinks/status
  verbs:
  - get