# permissions for end users to edit federatedmetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: federatedmetric-editor-role
rules:
- apiGroups:
  - metrics.openmcp.cloud
  resources:
  - federatedmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.openmcp.cloud
  resources:
  - federatedmetrics/status
  verbs:
  - get
