# permissions for end users to view federatedmanagedmetrics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: federatedmanagedmetric-viewer-role
rules:
- apiGroups:
  - metrics.openmcp.cloud
  resources:
  - federatedmanagedmetrics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.openmcp.cloud
  resources:
  - federatedmanagedmetrics/status
  verbs:
  - get
