---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - clusteraccesses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - clusteraccesses/finalizers
  verbs:
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - clusteraccesses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - compoundmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - compoundmetrics/finalizers
  verbs:
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - compoundmetrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - federatedmanagedmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - federatedmanagedmetrics/finalizers
  verbs:
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - federatedmanagedmetrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - federatedmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - federatedmetrics/finalizers
  verbs:
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - federatedmetrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - managedmetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - managedmetrics/finalizers
  verbs:
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - managedmetrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - metrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - metrics/finalizers
  verbs:
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - metrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - singlemetrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - singlemetrics/finalizers
  verbs:
  - update
- apiGroups:
  - insight.orchestrate.cloud.sap
  resources:
  - singlemetrics/status
  verbs:
  - get
  - patch
  - update
