---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - metrics.cloud.sap
  resources:
  - clusteraccesses
  - federatedmetrics
  - managedmetrics
  - metrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metrics.cloud.sap
  resources:
  - clusteraccesses/finalizers
  - federatedmetrics/finalizers
  - managedmetrics/finalizers
  - metrics/finalizers
  verbs:
  - update
- apiGroups:
  - metrics.cloud.sap
  resources:
  - clusteraccesses/status
  - federatedmetrics/status
  - managedmetrics/status
  - metrics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metrics.cloud.sap
  resources:
  - datasinks
  verbs:
  - get
  - list
  - watch
