---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - business.orchestrate.cloud.sap
  resources:
  - metrics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - business.orchestrate.cloud.sap
  resources:
  - metrics/finalizers
  verbs:
  - update
- apiGroups:
  - business.orchestrate.cloud.sap
  resources:
  - metrics/status
  verbs:
  - get
  - patch
  - update
