apiVersion: orchestrate.cloud.sap/v1alpha1
kind: RemoteClusterAccess
metadata:
  labels:
    app.kubernetes.io/name: metrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: remoteclusteraccess-sample
spec:
  # TODO(user): Add fields here
