apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: basic-metric
spec:
  name: helm-release-metric
  description: Helm Release Metric Helm Crossplane Provider
  target:
    kind: release
    group: helm.crossplane.io
    version: v1beta1
  interval: 1m # in minutes
  # Uses default DataSink (named "default" in metrics-operator-system namespace)
  # To use a custom DataSink, uncomment and specify:
  # dataSinkRef:
  #   name: default
---
apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: basic-pods
spec:
  name: pods-metric
  description: Pods
  target:
    kind: pod
    group: ""
    version: v1
  interval: 1m # in minutes
  projections:
    - name: pod-namespace
      fieldPath: "metadata.namespace"
---
apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: basic-total-pods
spec:
  name: pods-metric-total
  description: Pods
  target:
    kind: pod
    group: ""
    version: v1
  interval: 1m # in minutes
