apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: basic-metric
spec:
  name: helm-release-metric
  description: Helm Release Metric Helm Crossplane Provider
  kind: releases
  group: helm.crossplane.io
  version: v1beta1
  checkInterval: 1m # in minutes
---
apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: basic-pods
spec:
  name: pods-metric
  description: Pods
  kind: pods
  group: ""
  version: v1
  checkInterval: 1m # in minutes
  projections:
    - name: pod-namespace
      fieldPath: "metadata.namespace"
---
apiVersion: metrics.cloud.sap/v1alpha1
kind: Metric
metadata:
  name: basic-total-pods
spec:
  name: pods-metric-total
  description: Pods
  kind: pods
  group: ""
  version: v1
  checkInterval: 1m # in minutes

#apiVersion: metrics.cloud.sap/v1alpha1
#kind: Metric
#metadata:
#  name: ext-sa-metric
#spec:
#  name: ext-subaccount-metric
#  description: Subaccounts in mirza mcp cluster
#  kind: Subaccount
#  group: account.btp.orchestrate.cloud.sap
#  version: v1alpha1
#  frequency: 1 # in minutes
#  remoteClusterAccessRef:
#    name: remote-cluster-access
#    namespace: default
