apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: fooconfig
  namespace: default
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: default
  providerConfigRef:
    name: kubernetes-provider
---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: foonamespace
  namespace: default
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        namespace: default
  providerConfigRef:
    name: kubernetes-provider
