apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: co-monitor-co-metrics-operator
rules:
  - apiGroups:
      - cola.cloud.sap
    resources:
      - managedcontrolplanes
      - managedcontrolplanes/status
      - internalconfigurations
      - dataplanes
      - dataplanes/status
      - landscapers
      - landscapers/status
      - cloudorchestrators
      - cloudorchestrators/status
      - authentications
      - authentications/status
      - authorizations
      - authorizations/status
    verbs:
      - '*'
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: co-monitor-co-metrics-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: co-monitor-co-metrics-operator
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: dev-core:system:serviceaccount:co-metrics-operator:co-monitor-co-metrics-operator
