apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubeconfigs.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                kubeConfig:
                  type: string
                  description: "The kubeconfig to be stored"
              required:
                - kubeConfig
  scope: Namespaced
  names:
    plural: kubeconfigs
    singular: kubeconfig
    kind: KubeConfig
    shortNames:
      - kc
