name: Check Go Dependency Licenses

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - go.mod
      - go.sum

permissions:
  contents: read

jobs:
  validate:
    uses: openmcp-project/build/.github/workflows/go-license-check.lib.yaml@3051802a4f3fc6b250d6374b196075cec8390bf7 # main
    secrets: inherit
