name: Check Go Dependency Licenses

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - go.mod
      - go.sum

permissions:
  contents: read

jobs:
  validate:
    uses: openmcp-project/build/.github/workflows/go-license-check.lib.yaml@6e6df00f34641997459388343b33f4bb1cc964c6 # main
    secrets: inherit
