name: Check Go Dependency Licenses

on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - go.mod
      - go.sum

permissions:
  contents: read

jobs:
  validate:
    uses: openmcp-project/build/.github/workflows/go-license-check.lib.yaml@e6fddacd119db2136c40f9d5cca6a9ce3920b435 # main
    secrets: inherit
