name: Publish

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  packages: write

jobs:
  release_publish:
   uses: openmcp-project/build/.github/workflows/publish.lib.yaml@1dfe1496cdee935bf61006c706e5fd3ecd06b82e # main
   secrets: inherit