name: Versioned Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # we need this to be able to push tags
  pull-requests: read

jobs:
  release_tag:
    uses: openmcp-project/build/.github/workflows/release.lib.yaml@1dfe1496cdee935bf61006c706e5fd3ecd06b82e # main
    secrets: inherit
