name: REUSE Compliance Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  run_reuse:
    uses: openmcp-project/build/.github/workflows/reuse.lib.yaml@1dfe1496cdee935bf61006c706e5fd3ecd06b82e # main
    secrets: inherit
