name: Validate Pull Request Content

on:
  pull_request:
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validate_pr_content:
    uses: openmcp-project/build/.github/workflows/validate-pr-content.lib.yaml@1dfe1496cdee935bf61006c706e5fd3ecd06b82e # main
    secrets: inherit